### ISSUE TITLE
CSS with source maps comments break Sonar execution.

### ISSUE THREAD

**Issue by FJLopezGarcia** [SonarQubeCommunity/sonar-css#150]
Some CSS files contain an annotation that specifies the URL of its source map file, embedded in a special comment on the last line of the file. This special comment breaks the Sonar execution. Do you know how to fix it?

/*# sourceMappingURL=variables.css.map */

Sonar Issue:

[00:48:18] INFO: ------------------------------------------------------------------------

[00:48:18] INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 4.030s

[00:48:18] Final Memory: 11M/370M
INFO: ------------------------------------------------------------------------

[00:48:18] ERROR: Error during Sonar runner execution

[00:48:18] org.sonar.runner.impl.RunnerException: Unable to execute Sonar

[00:48:18] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)

[00:48:18] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
[00:48:18] 

[00:48:18] Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: /Users/franciscojlopez/Documents/GIT/DigitalIntModel_5228Git/Source/Web/Accenture.Dim.Web/app/css/acc-font.css
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)

[00:48:18] 	at org.sonar.plugins.css.CssSquidSensor.analyse(CssSquidSensor.java:91)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
[00:48:18] 
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
[00:48:18] 
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
[00:48:18] 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more

[00:48:18] Caused by: java.lang.IllegalArgumentException: Unable to highlight file [moduleKey=Rapid-Development-Offering:DIM-Portal:css_module, relative=acc-font.css, basedir=/Users/franciscojlopez/Documents/GIT/DigitalIntModel_5228Git/Source/Web/Accenture.Dim.Web/app/css] from offset 356528 to offset 356568
[00:48:18] 
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:85)

[00:48:18] 	at org.sonar.batch.source.DefaultHighlightable$DefaultHighlightingBuilder.highlight(DefaultHighlightable.java:79)
	at org.sonar.css.ast.visitors.SyntaxHighlighterVisitor.visitToken(SyntaxHighlighterVisitor.java:109)
	at com.sonar.sslr.impl.ast.AstWalker.visitToken(AstWalker.java:107)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:86)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
	... 35 more

[00:48:18] Caused by: java.lang.IllegalArgumentException: 356568 is not a valid offset for file [moduleKey=Rapid-Development-Offering:DIM-Portal:css_module, relative=acc-font.css, basedir=/Users/franciscojlopez/Documents/GIT/DigitalIntModel_5228Git/Source/Web/Accenture.Dim.Web/app/css]. Max offset is 356567

[00:48:18] 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:267)

[00:48:18] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:262)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:83)
	... 43 more

[00:48:18] Return code: 1.

/Users/franciscojlopez/Documents/GIT/DigitalIntModel_5228Git/Source/Web/Accenture.Dim.Web/node_modules/gulp-sonar/index.js:73
                        throw new PluginError('gulp-sonar', format('Return code: %d.', code));
                        ^
Error: Return code: 1.

**Comment by racodond** [comment]
Hi,

It looks like it is related to https://github.com/SonarQubeCommunity/sonar-css/issues/147

Could you please confirm?

Thanks

**Comment by FJLopezGarcia** [comment]
umm i am not sure if the issue is exactly the same. What i know is that when you remove the annotation located at the en of the CSS, the Sonar analysis runs properly.

Removing
/*# sourceMappingURL=variables.css.map */

Do you have a fix for that?

Thanks a lot

**Comment by racodond** [comment]
It is likely that your file is UTF-8 encoded and starting with a Byte Order Mark (BOM). This case might lead to some highligthing issue especially when the last characters of a file must be highlighted (the comments in your case)
