### ISSUE TITLE
IllegalArgumentException when analysing CSS-Files

### ISSUE THREAD

**Issue by Argelbargel** [SonarQubeCommunity/sonar-css#260]
I'm getting IllegalArgumentExceptions when/after analysing large CSS-Files:

java.lang.IllegalArgumentException: 223415 is not a valid line offset for pointer. File [moduleKey=<projectKey>, relative=<path/to/css-file.css> basedir=<path/to/basedir>] has 223414 character(s) at line 1
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:218)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:209)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:240)
	at org.sonar.css.issue.PreciseIssue.save(PreciseIssue.java:102)
	at org.sonar.plugins.css.CssSquidSensor.saveIssues(CssSquidSensor.java:121)
	at org.sonar.plugins.css.CssSquidSensor.save(CssSquidSensor.java:105)
	at org.sonar.plugins.css.CssSquidSensor.analyse(CssSquidSensor.java:89)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
	at org.sonarsource.scanner.cli.Main.main(Main.java:60)

Any ideas what might cause this?

**Comment by racodond** [comment]
Hi @Argelbargel,

Is the file encoded in UTF-8? Does it start with a Byte Order Mark (BOM)?
If so, you might be facing an issue related to https://github.com/SonarQubeCommunity/sonar-css/issues/252 that is fixed on the master branch. Could you build the jar from the master branch and run an analysis on your file? Or could you privately send the file to me?

Thank you

Have a good day!

**Comment by Argelbargel** [comment]
Hi @racodond,

i've tried to run an analysis with a jar built from the master branch and got the same error. I've sent you an email containing the problematic css-file.

Kind regards

Karsten

...and a good day to you, too! ;-)

**Comment by racodond** [comment]
Hi @Argelbargel,

The file you sent is encoded in UTF-8 and starts with a Byte Order Mark.
I analyze it on my side and it works fine.
Did you set the `sonar.sourceEncoding` analysis paramter to `UTF-8`?

Thank you

David

**Comment by Argelbargel** [comment]
Hi @racodond,

yes, sonar.sourceEncoding is set to UTF-8 and all files have the correct encoding (according to the IDE). Perhaps the error is caused by a combination of css-files? I could send you the complete tree of our css-files if that helps...

Kind regards

Karsten

**Comment by racodond** [comment]
Yes, please send all the files so that I can try to reproduce your issue. Could you also send the full log of the analysis?

Thank you 

David

**Comment by racodond** [comment]
@Argelbargel Ping! :-)
