### ISSUE TITLE
Fix failing build on Windows

### ISSUE THREAD

**Issue by racodond** [SonarQubeCommunity/sonar-css#295]
See https://ci.appveyor.com/project/racodond/sonar-css/branch/master

**Comment by mslama-work** [comment]
Is it problem with failing plugin tests during build? (The same issue on Win and Linux). I just want to avoid filing duplicate issue.

`Tests run: 8, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 1.138 sec <<< FAILURE! - in org.sonar.plugins.css.CssSquidSensorTest
should_execute_and_compute_valid_measures_on_file_starting_with_BOM(org.sonar.plugins.css.CssSquidSensorTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.NullPointerException: null
        at org.sonar.plugins.css.CssSquidSensorTest.assertMeasures(CssSquidSensorTest.java:76)
        at org.sonar.plugins.css.CssSquidSensorTest.should_execute_and_compute_valid_measures_on_file_starting_with_BOM(CssSquidSensorTest.java:72)

should_execute_and_save_issues_on_file_starting_with_BOM(org.sonar.plugins.css.CssSquidSensorTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected size:<3> but was:<0> for <[]>
        at org.fest.assertions.Fail.failure(Fail.java:228)
        at org.fest.assertions.Assert.failure(Assert.java:149)
        at org.fest.assertions.GroupAssert.hasSize(GroupAssert.java:89)
        at org.sonar.plugins.css.CssSquidSensorTest.should_execute_and_save_issues(CssSquidSensorTest.java:108)
        at org.sonar.plugins.css.CssSquidSensorTest.should_execute_and_save_issues_on_file_starting_with_BOM(CssSquidSensorTest.java:92)
`

**Comment by racodond** [comment]
@mslama-work : It is this issue about failing tests on files with Byte Order Mark (BOM). It is on Windows only. It works fine on Linux. I didn't have time to investigate yet.

**Comment by mslama-work** [comment]
Ok. I wait and retest once fix is committed. Thanks.

**Comment by racodond** [comment]
Moved to https://github.com/racodond/sonar-css-plugin/issues/4
